---
sidebar: sidebar 
permalink: faq.html 
keywords: community, forums, help, support, videos, faq, getting help, permissions, access control lists, acls, preserve, preserving, troubleshooting, support, encryption, smb 
summary: 您可以透過各種資源（包括論壇、聊天服務和影片）取得有關NetApp Copy and Sync的協助並尋找更多資訊。 
---
= NetApp Copy and Sync技術常見問題解答
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想快速找到問題的答案，此常見問題解答可以為您提供協助。



[[getting-started]]
== 入門

以下問題與開始使用NetApp Copy and Sync有關。



[[how-does-netapp-copy-and-sync-work]]
=== NetApp Copy and Sync如何運作？

複製並同步使用NetApp資料代理軟體將資料從來源同步到目標（這稱為_同步關係_）。

資料代理組控制來源和目標之間的同步關係。設定同步關係後，複製和同步會分析您的來源系統並將其分解為多個複製流以推送到您選擇的目標資料。

初始複製後，「複製和同步」會根據您設定的計劃同步任何變更的資料。



[[how-does-the-14-day-free-trial-work]]
=== 14 天免費試用如何進行？

當您註冊 Copy and Sync 時，14 天的免費試用期就開始了。您無需為 14 天內建立的複製和同步關係支付NetApp費用。但是，您部署的任何資料代理程式的所有資源費用仍然適用。



[[how-much-does-copy-and-sync-cost]]
=== 複製和同步的費用是多少？

使用複製和同步有兩種類型的成本：服務費和資源費。

*服務費*

對於按使用量付費的定價，複製和同步服務費用按小時計算，取決於您創建的同步關係的數量。

* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["查看 AWS 中的按使用量付費定價"^]
* https://aws.amazon.com/marketplace/pp/B06XX5V3M2["查看 AWS 中的年度定價"^]
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["查看 Azure 中的定價"^]


您也可以透過NetApp代表取得複製和同步授權。每個許可證可支援 12 個月的 20 個同步關係。

link:concept-licensing.html["了解有關許可證的更多信息"] 。


NOTE: 對於Azure NetApp Files來說，複製和同步關係是免費的。

*資源費用*

資源費用與在雲端中運行資料代理程式的運算和儲存成本有關。



[[how-is-copy-and-sync-billed-and-how-do-i-manage-my-subscription]]
=== 複製和同步如何計費以及如何管理我的訂閱？

14 天免費試用期結束後，您可以透過兩種方式支付同步關係費用。第一個選項是從 AWS 或 Azure 訂閱，這樣您就可以按使用量付費或按年付費。第二種選擇是直接從NetApp購買許可證。在每種情況下，您的訂閱都將透過您的供應商市場進行管理，而不是透過複製和同步使用者介面進行管理。



[[can-i-use-copy-and-sync-outside-the-cloud]]
=== 我可以在雲端外使用複製和同步嗎？

是的，您可以在非雲端架構中使用複製和同步。來源和目標可以駐留在本地，資料代理軟體也可以駐留在本地。

請注意有關在雲端外使用複製和同步的以下要點：

* 數據經紀人團體需要網路連線才能與複製和同步進行通訊。
* 如果您不直接從NetApp購買許可證，則需要一個 AWS 或 Azure 帳戶來進行 PAYGO Copy and Sync 計費。




[[how-do-i-access-copy-and-sync]]
=== 如何存取複製和同步？

可以從NetApp Console進行複製和同步。從控制台左側導覽中，選擇*移動性*>*複製和同步*。



[[whats-a-data-broker-group]]
=== 什麼是數據經紀人團體？

每個數據經紀人都屬於數據經紀人組。將資料代理分組在一起有助於提高同步關係的效能。



[[supported-sources-and-targets]]
== 支持的來源和目標

以下問題與同步關係中支援的來源和目標有關。



[[which-sources-and-targets-does-copy-and-sync-support]]
=== 複製和同步支援哪些來源和目標？

複製和同步支援多種不同類型的同步關係。link:reference-supported-relationships.html["查看完整列表"] 。



[[what-versions-of-nfs-and-smb-does-copy-and-sync-support]]
=== 複製和同步支援哪些版本的 NFS 和 SMB？

複製和同步支援 NFS 版本 3 及更高版本以及 SMB 版本 1 及更高版本。

link:reference-requirements.html["詳細了解同步要求"] 。



[[when-amazon-s3-is-the-target-can-the-data-be-tiered-to-a-specific-s3-storage-class]]
=== 當以 Amazon S3 為目標時，資料可以分層到特定的 S3 儲存類別嗎？

是的，當 AWS S3 是目標時，您可以選擇特定的 S3 儲存類別：

* 標準（這是預設類別）
* 智能分層
* 標準-不頻繁訪問
* 單區-不頻繁訪問
* 冰川深度檔案
* 冰川彈性檢索
* 冰川即時檢索




[[what-about-storage-tiers-for-azure-blob-storage]]
=== Azure Blob 儲存體的儲存層怎麼樣？

當 Blob 容器是目標時，您可以選擇特定的 Azure Blob 儲存層：

* 熱儲存
* 冷藏




[[do-you-support-google-cloud-storage-tiers]]
=== 您是否支援 Google Cloud 儲存層？

是的，當 Google Cloud Storage 儲存桶是目標時，您可以選擇特定的儲存類別：

* 標準
* 近線
* 涼線
* 檔案




[[networking]]
== 聯網

以下問題與複製和同步的網路要求有關。



[[what-are-the-networking-requirements-for-copy-and-sync]]
=== 複製和同步的網路要求是什麼？

複製和同步環境要求資料代理組透過所選協定或物件儲存 API（Amazon S3、Azure Blob、IBM Cloud Object Storage）與來源和目標連接。

此外，資料代理群組需要透過連接埠 443 建立出站互聯網連接，以便與複製和同步進行通訊並聯繫其他一些服務和儲存庫。

欲了解更多詳情，link:reference-networking.html["審查網路要求"] 。



[[can-i-use-a-proxy-server-with-the-data-broker]]
=== 我可以將代理伺服器與資料代理一起使用嗎？

是的。

複製和同步支援有或沒有基本驗證的代理伺服器。如果在部署資料代理程式時指定代理伺服器，則來自資料代理程式的所有 HTTP 和 HTTPS 流量都將透過代理程式路由。請注意，非 HTTP 流量（例如 NFS 或 SMB）不能透過代理伺服器路由。

唯一的代理伺服器限制是使用具有 NFS 或Azure NetApp Files同步關係的動態資料加密時。加密資料透過 HTTPS 傳送，無法透過代理伺服器路由。



[[data-synchronization]]
== 資料同步

以下問題與資料同步的工作原理有關。



[[how-often-does-synchronization-occur]]
=== 同步發生的頻率是多少？

預設計劃設定為每日同步。初始同步後，您可以：

* 將同步計劃修改為所需的天數、小時數或分鐘數
* 停用同步計劃
* 刪除同步計劃（不會遺失任何資料；只會刪除同步關係）




[[what-is-the-minimum-sync-schedule]]
=== 最小同步計劃是多少？

您可以安排每 1 分鐘同步一次資料。



[[does-the-data-broker-group-retry-when-a-file-fails-to-sync-or-does-it-timeout]]
=== 當檔案同步失敗時，資料代理組是否會重試？或者它超時了嗎？

當單一檔案傳輸失敗時，資料代理組不會逾時。相反，資料代理組在跳過該檔案之前會重試 3 次。重試值可以在同步關係的設定中配置。

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["了解如何變更同步關係的設置"] 。



[[what-if-i-have-a-very-large-dataset]]
=== 如果我有一個非常大的資料集怎麼辦？

如果單一目錄包含 600,000 個或更多文件，link:task-get-help.html["聯絡我們"]以便我們可以幫助您配置資料代理組來處理有效負載。我們可能需要向資料代理組添加額外的記憶體。

請注意，掛載點中的檔案總數沒有限制。對於包含 600,000 個或更多檔案的大型目錄，無論其在層次結構中的層級（頂級目錄或子目錄）如何，都需要額外的記憶體。



[[security]]
== 安全

以下問題與安全有關。



[[is-copy-and-sync-secure]]
=== 複製和同步安全嗎？

是的。所有複製和同步網路連線均使用 https://aws.amazon.com/sqs/["亞馬遜簡單佇列服務 (SQS)"^]。

資料代理組與 Amazon S3、Azure Blob、Google Cloud Storage 和 IBM Cloud Object Storage 之間的所有通訊均透過 HTTPS 協定完成。

如果您將複製和同步功能與本機（來源或目標）系統一起使用，則建議使用以下幾個連線選項：

* AWS Direct Connect、Azure ExpressRoute 或 Google Cloud Interconnect 連接，非互聯網路由（且只能與您指定的雲端網路通訊）
* 本地網關設備與雲端網路之間的 VPN 連接
* 為了使用 S3 儲存桶、Azure Blob 儲存體或 Google Cloud Storage 進行額外的安全資料傳輸，可以建立 Amazon Private S3 Endpoint、Azure Virtual Network 服務端點或 Private Google Access。


這些方法中的任何一種都會在您的本機 NAS 伺服器和複製和同步資料代理群組之間建立安全連線。



[[is-data-encrypted-by-copy-and-sync]]
=== 複製和同步是否加密資料？

* 複製和同步支援來源和目標 NFS 伺服器之間的資料傳輸加密。link:task-nfs-encryption.html["了解更多"] 。
* 對於 SMB，複製和同步支援您在伺服器端加密的 SMB 3.0 和 3.11 資料。複製和同步將加密資料從來源複製到目標，資料在目標中保持加密狀態。
+
複製和同步本身無法加密 SMB 資料。

* 當 Amazon S3 儲存桶是同步關係中的目標時，您可以選擇使用 AWS KMS 加密或 AES-256 加密來啟用資料加密。
* 當 Google 儲存桶是同步關係中的目標時，您可以選擇使用預設的 Google 管理的加密金鑰還是您自己的 KMS 金鑰。




[[permissions]]
== 權限

以下問題與資料權限有關。



[[are-smb-data-permissions-synced-to-the-target-location]]
=== SMB 資料權限是否同步到目標位置？

您可以設定複製和同步以保留來源 SMB 共用和目標 SMB 共用之間以及從來源 SMB 共用到物件儲存（ ONTAP S3 除外）的存取控制清單 (ACL)。


NOTE: 複製和同步不支援將 ACL 從物件儲存複製到 SMB 共用。

link:task-copying-acls.html["了解如何在 SMB 共用之間複製 ACL"] 。


NOTE: Copy Sync 會複製 SMB ACL（權限），但不會複製檔案或資料夾的擁有權。 SMB ACL 複製作業不包含所有權屬性。如果在 SMB 共用之間複製資料時需要保留所有權，請使用 `robocopy`手動複製安全資訊。例如， `/copyall`標記副本 ACL、所有者和審計資料。



[[are-nfs-data-permissions-synced-to-the-target-location]]
=== NFS 資料權限是否同步到目標位置？

複製和同步會自動在 NFS 伺服器之間複製 NFS 權限，如下所示：

* NFS 版本 3：複製和同步複製權限和使用者群組擁有者。
* NFS 版本 4：複製和同步複製 ACL。




[[object-storage-metadata]]
== 物件儲存元數據



[[what-kinds-of-sync-relationships-preserve-object-storage-metadata]]
=== 哪些類型的同步關係可以保留物件儲存元資料？

複製和同步將物件儲存元資料從來源複製到目標，以實現以下類型的同步關係：

* 亞馬遜 S3 -> 亞馬遜 S3 ^1^
* Amazon S3 -> StorageGRID
* StorageGRID-> Amazon S3
* StorageGRID->StorageGRID
* StorageGRID -> Google 雲端存儲
* Google 雲端儲存 -> StorageGRID ^1^
* Google 雲端儲存 -> IBM 雲端物件儲存 ^1^
* Google 雲端儲存 -> Amazon S3 ^1^
* 亞馬遜 S3 -> 谷歌雲端存儲
* IBM 雲端物件儲存 -> Google 雲端存儲
* StorageGRID -> IBM 雲端物件存儲
* IBM 雲端物件儲存 -> StorageGRID
* IBM 雲端物件儲存 -> IBM 雲端物件存儲


^1^ 對於這些同步關係，您需要link:task-creating-relationships.html["建立同步關係時啟用「物件複製」設置"]。



[[what-kinds-of-metadata-are-replicated-during-syncs-where-nfs-or-smb-are-the-source]]
=== 在以 NFS 或 SMB 為來源的同步過程中，會複製哪些類型的元資料？

預設會複製使用者 ID、修改時間、存取時間和 GID 等元資料。使用者可以在建立同步關係時將其標記為必需，從而選擇從 CIF 複製 ACL。



[[performance]]
== 表現

以下問題與複製和同步效能有關。



[[what-does-the-progress-indicator-for-a-sync-relationship-represent]]
=== 同步關係的進度指示器代表什麼？

同步關係顯示資料代理組網路適配器的吞吐量。如果您使用多個資料代理來加速同步效能，那麼吞吐量就是所有流量的總和。此吞吐量每 20 秒刷新一次。



[[im-experiencing-performance-issues-can-we-limit-the-number-of-concurrent-transfers]]
=== 我遇到了效能問題。我們可以限制並發傳輸的數量嗎？

如果您有非常大的檔案（每個檔案有多個 TiB），則完成傳輸過程可能需要很長時間，並且效能可能會受到影響。

限制並發傳輸的數量可能會有所幫助。link:task-get-help.html["聯絡我們尋求協助"] 。



[[why-am-i-experiencing-low-performance-with-azure-netapp-files]]
=== 為什麼我的Azure NetApp Files效能低？

當您將資料同步至Azure NetApp Files或從 Azure NetApp Files 同步資料時，如果磁碟服務等級為標準，則可能會遇到故障和效能問題。

將服務等級變更為 Premium 或 Ultra 以增強同步效能。

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels#throughput-limits["詳細了解Azure NetApp Files服務等級與吞吐量"^] 。



[[how-many-data-brokers-are-required-in-a-group]]
=== 一個集團需要多少個數據經紀人？

當您建立新的關係時，您會從群組中的單一資料代理程式開始（除非您選擇了屬於加速同步關係的現有資料代理程式）。在許多情況下，單一資料代理程式可以滿足同步關係的效能要求。如果沒有，您可以透過向群組中新增額外的資料代理程式來加速同步效能。但您應該先檢查可能影響同步效能的其他因素。

多種因素會影響資料傳輸效能。整體同步效能可能會受到網路頻寬、延遲和網路拓撲以及資料代理 VM 規格和儲存系統效能的影響。例如，一個群組中的單一資料代理程式可以達到 100 MB/s，而目標上的磁碟吞吐量可能只允許 64 MB/s。結果，數據經紀商集團不斷嘗試複製數據，但目標無法滿足數據經紀商集團的表現。

因此，請務必檢查網路效能和目標磁碟吞吐量。

然後，您可以考慮透過在群組中新增額外的資料代理來分擔該關係的負載，從而加速同步效能。link:task-managing-relationships.html#accelerate-sync-performance["了解如何加速同步效能"] 。



[[deleting-things]]
== 刪除內容

以下問題與從來源和目標刪除同步關係和資料有關。



[[what-happens-if-i-delete-my-copy-and-sync-relationship]]
=== 如果我刪除複製和同步關係會發生什麼？

刪除關係將停止所有未來的資料同步並終止付款。同步到目標的任何資料都保持原樣。



[[what-happens-if-i-delete-something-from-my-source-server-is-it-removed-from-the-target-too]]
=== 如果我從來源伺服器中刪除某些內容會發生什麼？它也從目標中移除了嗎？

預設情況下，如果您具有活動的同步關係，則在來源伺服器上刪除的項目不會在下次同步期間從目標伺服器上刪除。但是每個關係的同步設定中都有一個選項，您可以在其中定義如果從來源中刪除了文件，則複製和同步將刪除目標位置中的文件。

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["了解如何變更同步關係的設置"] 。



[[what-happens-if-i-delete-something-from-my-target-is-it-removed-from-my-source-too]]
=== 如果我從目標中刪除某些內容會發生什麼？它也從我的來源中刪除了嗎？

如果從目標中刪除某個項目，則它不會從來源中刪除。這種關係是單向的－從源頭到目標。在下一個同步週期中，「複製和同步」會將來源與目標進行比較，識別出該項目缺失，然後「複製和同步」會再次將其從來源複製到目標。



[[troubleshooting]]
== 故障排除

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Sync/Cloud_Sync_FAQ:_Support_and_Troubleshooting["NetApp知識庫：複製與同步常見問題：支援與故障排除"^]



[[data-broker-deep-dive]]
== 數據經紀人深度探究

以下問題與數據經紀人有關。



[[can-you-explain-the-architecture-of-the-data-broker]]
=== 您能解釋一下數據代理的架構嗎？

當然。以下是最重要的幾點：

* 資料代理程式是在 Linux 主機上執行的 node.js 應用程式。
* Copy and Sync 如下部署資料代理程式：
+
** AWS：來自 AWS CloudFormation 模板
** Azure：來自 Azure 資源管理器
** Google：來自 Google Cloud Deployment Manager
** 如果使用自己的Linux主機，則需要手動安裝軟體


* 數據代理軟體會自動升級到最新版本。
* 資料代理程式使用 AWS SQS 作為可靠、安全的通訊管道並用於控制和監控。  SQS 也提供了持久層。
* 您可以為群組中新增額外的資料代理程式以提高傳輸速度並增加高可用性。如果一個資料代理發生故障，則服務具有彈性。

