---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: 14 天免費試用期結束後，有兩種方式可以支付同步關係的費用。第一個選擇是現收現付。第二種選擇是直接從NetApp購買許可證。 
---
= NetApp Copy and Sync 免費試用期結束後，支付同步關係費用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Copy and Sync 的 14 天免費試用期結束後，有兩種方式可以支付同步關係的費用。第一個選項是從 AWS 或 Azure 訂閱，按使用量付費或按年付費。第二種選擇是直接從NetApp購買許可證。

您可以從 AWS Marketplace 或 Azure Marketplace 訂閱。您不能同時訂閱兩者。

您可以選擇透過市場訂閱使用NetApp的授權。例如，如果您有 25 個同步關係，則可以使用授權支付前 20 個同步關係的費用，然後使用剩餘的 5 個同步關係從 AWS 或 Azure 按使用量付費。

link:concept-licensing.html["詳細了解許可證的運作方式"] 。

如果您在免費試用期結束後沒有立即付款，您將無法建立任何其他關係。現有的關係不會被刪除，但在您訂閱或輸入許可證之前，您不能對其進行任何更改。

授權應透過NetApp Copy and Sync 或適用網站進行管理，而非透過NetApp Console 訂閱進行管理。



== [[aws]]從 AWS 訂閱

AWS 可讓您按使用量付費或按年付費。

.即用即付的步驟
. 從NetApp控制台導覽選單中，選擇 *Mobility > Copy and Sync*。
. 選擇*許可*。
. 選擇 *AWS*。
. 選擇*訂閱*，然後選擇*繼續*。
. 從 AWS Marketplace 訂閱，然後重新登入 Copy and Sync 完成註冊。
+
以下影片展示了這個過程：

+
.從 AWS Marketplace 訂閱複製和同步
video::796ffd6d-cade-4750-8504-b24c010b225d[panopto]


.每年付款的步驟
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["前往 AWS Marketplace 頁面"^] 。
. 選擇*繼續訂閱*。
. 選擇您的合約選項，然後選擇*建立合約*。




== [[azure]]從 Azure 訂閱

Azure 可讓您按使用量付費或按年付費。

.你需要什麼
在相關訂閱中具有貢獻者或擁有者權限的 Azure 使用者帳戶。

.步驟
. 從NetApp控制台導覽選單中，選擇 *Mobility > Copy and Sync*。
. 選擇*許可*。
. 選擇“*Azure*”。
. 選擇*訂閱*，然後選擇*繼續*。
. 在 Azure 入口網站中，選擇“*建立*”，選擇您的選項，然後選擇“*訂閱*”。
+
選擇「每月」按小時付費，或選擇「每年」預付一年的費用。

. 部署完成後，在通知彈出視窗中選擇 SaaS 資源的名稱。
. 選擇“配置帳戶”返回“複製和同步”。
+
以下影片展示了這個過程：

+
.從 Azure 市場訂閱複製和同步
video::a6a39447-b7b1-42f6-9c89-b24c010b21b9[panopto]




== [[licenses]]從NetApp購買許可證並將其添加到複製和同步

要預先支付同步關係的費用，您必須購買一個或多個許可證並將其添加到複製和同步中。

.你需要什麼
您需要許可證的序號以及與該許可證關聯的NetApp支援網站帳戶的使用者名稱和密碼。

.步驟
. 透過 mailto:ng-cloudsync-contact@netapp.com?subject=Cloud%20Sync%20Service%20-%20BYOL%20License%20Purchase%20Request[聯絡NetApp] 購買授權。
. link:task-login-copyandsync.html["登入以複製和同步"] 。
. 選擇*許可*。
. 選擇*新增許可證*並新增所需資訊：
+
.. 輸入序號。
.. 選擇與您要新增的許可證關聯的NetApp支援網站帳戶：
+
*** 如果您的帳戶已新增至NetApp控制台，請從下拉清單中選擇它。
*** 如果您的帳戶尚未新增，請選擇*新增 NSS 憑證*，輸入使用者名稱和密碼，選擇*註冊*，然後從下拉清單中選擇它。


.. 選擇“*新增*”。






== 更新許可證

如果您延長了從NetApp購買的複製和同步許可證，則新的到期日期將不會在複製和同步中自動更新。您需要重新新增許可證以刷新到期日期。許可證應透過複製和同步或適用的網站進行管理，而不是透過NetApp控制台訂閱進行管理。

.步驟
. 從NetApp控制台導覽選單中，選擇 *Mobility > Copy and Sync*。
. 選擇*許可*。
. 選擇*新增許可證*並新增所需資訊：
+
.. 輸入序號。
.. 選擇與您要新增的許可證關聯的NetApp支援網站帳戶。
.. 選擇“*新增*”。




.結果
複製和同步會使用新的到期日更新現有許可證。
